# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vehicle.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rvehicle.proto\x12\x02pb\"\x1b\n\rPV_GetVehicle\x12\n\n\x02id\x18\x01 \x01(\t\".\n\rVP_GetVehicle\x12\x1d\n\x04info\x18\x01 \x01(\x0b\x32\x0f.pb.VehicleInfo\"\x1d\n\x0fPV_GetNeigbours\x12\n\n\x02id\x18\x01 \x01(\t\">\n\x0fVP_GetNeigbours\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1f\n\tneigbours\x18\x02 \x03(\x0b\x32\x0c.pb.Neigbour\"X\n\x08Neigbour\x12\x1d\n\x04info\x18\x01 \x01(\x0b\x32\x0f.pb.VehicleInfo\x12\x12\n\nis_forward\x18\x02 \x01(\x08\x12\x19\n\x11is_same_direction\x18\x03 \x01(\x08\"~\n\x0bVehicleInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\x0f\n\x07speed_x\x18\x05 \x01(\x01\x12\x0f\n\x07speed_y\x18\x06 \x01(\x01\x12\x0f\n\x07speed_z\x18\x07 \x01(\x01\x12\x0f\n\x07heading\x18\x08 \x01(\x01\x62\x06proto3'
)




_PV_GETVEHICLE = _descriptor.Descriptor(
  name='PV_GetVehicle',
  full_name='pb.PV_GetVehicle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.PV_GetVehicle.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=48,
)


_VP_GETVEHICLE = _descriptor.Descriptor(
  name='VP_GetVehicle',
  full_name='pb.VP_GetVehicle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pb.VP_GetVehicle.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=96,
)


_PV_GETNEIGBOURS = _descriptor.Descriptor(
  name='PV_GetNeigbours',
  full_name='pb.PV_GetNeigbours',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.PV_GetNeigbours.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=127,
)


_VP_GETNEIGBOURS = _descriptor.Descriptor(
  name='VP_GetNeigbours',
  full_name='pb.VP_GetNeigbours',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.VP_GetNeigbours.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neigbours', full_name='pb.VP_GetNeigbours.neigbours', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=191,
)


_NEIGBOUR = _descriptor.Descriptor(
  name='Neigbour',
  full_name='pb.Neigbour',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pb.Neigbour.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_forward', full_name='pb.Neigbour.is_forward', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_same_direction', full_name='pb.Neigbour.is_same_direction', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=281,
)


_VEHICLEINFO = _descriptor.Descriptor(
  name='VehicleInfo',
  full_name='pb.VehicleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.VehicleInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='pb.VehicleInfo.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='pb.VehicleInfo.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='pb.VehicleInfo.z', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_x', full_name='pb.VehicleInfo.speed_x', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_y', full_name='pb.VehicleInfo.speed_y', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_z', full_name='pb.VehicleInfo.speed_z', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heading', full_name='pb.VehicleInfo.heading', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=409,
)

_VP_GETVEHICLE.fields_by_name['info'].message_type = _VEHICLEINFO
_VP_GETNEIGBOURS.fields_by_name['neigbours'].message_type = _NEIGBOUR
_NEIGBOUR.fields_by_name['info'].message_type = _VEHICLEINFO
DESCRIPTOR.message_types_by_name['PV_GetVehicle'] = _PV_GETVEHICLE
DESCRIPTOR.message_types_by_name['VP_GetVehicle'] = _VP_GETVEHICLE
DESCRIPTOR.message_types_by_name['PV_GetNeigbours'] = _PV_GETNEIGBOURS
DESCRIPTOR.message_types_by_name['VP_GetNeigbours'] = _VP_GETNEIGBOURS
DESCRIPTOR.message_types_by_name['Neigbour'] = _NEIGBOUR
DESCRIPTOR.message_types_by_name['VehicleInfo'] = _VEHICLEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PV_GetVehicle = _reflection.GeneratedProtocolMessageType('PV_GetVehicle', (_message.Message,), {
  'DESCRIPTOR' : _PV_GETVEHICLE,
  '__module__' : 'vehicle_pb2'
  # @@protoc_insertion_point(class_scope:pb.PV_GetVehicle)
  })
_sym_db.RegisterMessage(PV_GetVehicle)

VP_GetVehicle = _reflection.GeneratedProtocolMessageType('VP_GetVehicle', (_message.Message,), {
  'DESCRIPTOR' : _VP_GETVEHICLE,
  '__module__' : 'vehicle_pb2'
  # @@protoc_insertion_point(class_scope:pb.VP_GetVehicle)
  })
_sym_db.RegisterMessage(VP_GetVehicle)

PV_GetNeigbours = _reflection.GeneratedProtocolMessageType('PV_GetNeigbours', (_message.Message,), {
  'DESCRIPTOR' : _PV_GETNEIGBOURS,
  '__module__' : 'vehicle_pb2'
  # @@protoc_insertion_point(class_scope:pb.PV_GetNeigbours)
  })
_sym_db.RegisterMessage(PV_GetNeigbours)

VP_GetNeigbours = _reflection.GeneratedProtocolMessageType('VP_GetNeigbours', (_message.Message,), {
  'DESCRIPTOR' : _VP_GETNEIGBOURS,
  '__module__' : 'vehicle_pb2'
  # @@protoc_insertion_point(class_scope:pb.VP_GetNeigbours)
  })
_sym_db.RegisterMessage(VP_GetNeigbours)

Neigbour = _reflection.GeneratedProtocolMessageType('Neigbour', (_message.Message,), {
  'DESCRIPTOR' : _NEIGBOUR,
  '__module__' : 'vehicle_pb2'
  # @@protoc_insertion_point(class_scope:pb.Neigbour)
  })
_sym_db.RegisterMessage(Neigbour)

VehicleInfo = _reflection.GeneratedProtocolMessageType('VehicleInfo', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLEINFO,
  '__module__' : 'vehicle_pb2'
  # @@protoc_insertion_point(class_scope:pb.VehicleInfo)
  })
_sym_db.RegisterMessage(VehicleInfo)


# @@protoc_insertion_point(module_scope)
